export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const REGISTRAR_CLIENTE = "REGISTRAR_CLIENTE";
export const OBTENER_CLIENTE = "OBTENER_CLIENTE";
export const MODIFICAR_CLIENTE = "MODIFICAR_CLIENTE";
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE";

//paramEdad
export const OBTENER_EDADES = "OBTENER_EDADES";
export const REGISTRAR_EDAD = "REGISTRAR_EDAD";
export const OBTENER_EDAD = "OBTENER_EDAD";
export const MODIFICAR_EDAD = "MODIFICAR_EDAD";
export const ELIMINAR_EDAD = "ELIMINAR_EDAD";

export const OBTENER_ANIOS = "OBTENER_ANIOS";
export const REGISTRAR_ANIO = "REGISTRAR_ANIO";
export const OBTENER_ANIO = "OBTENER_ANIO";
export const MODIFICAR_ANIO = "MODIFICAR_ANIO";
export const ELIMINAR_ANIO = "ELIMINAR_ANIO";

export const OBTENER_DESTREZAS = "OBTENER_DESTREZAS";
export const REGISTRAR_DESTREZA = "REGISTRAR_DESTREZA";
export const OBTENER_DESTREZA = "OBTENER_DESTREZA";
export const MODIFICAR_DESTREZA = "MODIFICAR_DESTREZA";
export const ELIMINAR_DESTREZA = "ELIMINAR_DESTREZA";
